---
# Modern Common Role - Essential Variables Only
# Focus on what's truly needed for base system setup

# Admin users to create with sudo access
common_admin_users: []
#  - name: admin
#    ssh_keys:
#      - "ssh-rsa AAAAB3... admin@example.com"
#    sudo_nopasswd: false

# Essential packages (will merge with OS defaults)
common_packages: []

# System configuration
common_timezone: "UTC"
common_hostname: "{{ inventory_hostname }}"

# SSH security (enabled by default)
common_harden_ssh: true
common_ssh_port: 22
common_disable_root_login: true
common_ssh_password_auth: false

# Basic security (enabled by default)
common_update_packages: true
common_install_security_packages: true
