---
# Architecture mapping for downloads
monitoring_arch_map:
  x86_64: "amd64"
  aarch64: "arm64"
  armv7l: "armv7"

# Package names by OS family
monitoring_package_names:
  Debian: "prometheus-node-exporter"
  RedHat: "golang-github-prometheus-node-exporter"
