---
# Security packages
security_packages:
  - auditd
  - aide
  - rkhunter

# CONSOLIDATED: All kernel security parameters from common role
security_kernel_params:
  basic:
    # Network security
    net.ipv4.ip_forward: 0
    net.ipv4.conf.all.send_redirects: 0
    net.ipv4.conf.all.accept_redirects: 0
    net.ipv4.conf.all.secure_redirects: 0
    net.ipv4.icmp_echo_ignore_broadcasts: 1
    net.ipv4.conf.all.log_martians: 1
    net.ipv4.conf.default.log_martians: 1
    # Kernel security
    kernel.dmesg_restrict: 1
    kernel.kptr_restrict: 1

  moderate:
    # Network security (enhanced)
    net.ipv4.ip_forward: 0
    net.ipv4.conf.all.send_redirects: 0
    net.ipv4.conf.all.accept_redirects: 0
    net.ipv4.conf.all.secure_redirects: 0
    net.ipv4.conf.default.send_redirects: 0
    net.ipv4.conf.default.accept_redirects: 0
    net.ipv4.conf.default.secure_redirects: 0
    net.ipv6.conf.all.accept_redirects: 0
    net.ipv6.conf.default.accept_redirects: 0
    net.ipv4.icmp_echo_ignore_broadcasts: 1
    net.ipv4.conf.all.log_martians: 1
    net.ipv4.conf.default.log_martians: 1
    # Kernel security (enhanced)
    kernel.dmesg_restrict: 1
    kernel.kptr_restrict: 2
    kernel.yama.ptrace_scope: 1
    # Filesystem security
    fs.suid_dumpable: 0
    fs.protected_hardlinks: 1
    fs.protected_symlinks: 1

  strict:
    # Network security (maximum)
    net.ipv4.ip_forward: 0
    net.ipv4.conf.all.send_redirects: 0
    net.ipv4.conf.all.accept_redirects: 0
    net.ipv4.conf.all.secure_redirects: 0
    net.ipv4.conf.default.send_redirects: 0
    net.ipv4.conf.default.accept_redirects: 0
    net.ipv4.conf.default.secure_redirects: 0
    net.ipv6.conf.all.accept_redirects: 0
    net.ipv6.conf.default.accept_redirects: 0
    net.ipv4.icmp_echo_ignore_broadcasts: 1
    net.ipv4.conf.all.log_martians: 1
    net.ipv4.conf.default.log_martians: 1
    # Kernel security (maximum)
    kernel.dmesg_restrict: 1
    kernel.kptr_restrict: 2
    kernel.yama.ptrace_scope: 2
    kernel.unprivileged_bpf_disabled: 1
    net.core.bpf_jit_harden: 2
    # Filesystem security (maximum)
    fs.suid_dumpable: 0
    fs.protected_hardlinks: 1
    fs.protected_symlinks: 1
    fs.protected_fifos: 2
    fs.protected_regular: 2

# Security limits by compliance level
security_limits:
  basic:
    - { domain: "*", type: "soft", item: "core", value: "0" }
    - { domain: "*", type: "hard", item: "core", value: "0" }

  moderate:
    - { domain: "*", type: "soft", item: "core", value: "0" }
    - { domain: "*", type: "hard", item: "core", value: "0" }
    - { domain: "*", type: "soft", item: "nproc", value: "32768" }
    - { domain: "*", type: "hard", item: "nproc", value: "32768" }

  strict:
    - { domain: "*", type: "soft", item: "core", value: "0" }
    - { domain: "*", type: "hard", item: "core", value: "0" }
    - { domain: "*", type: "soft", item: "nproc", value: "16384" }
    - { domain: "*", type: "hard", item: "nproc", value: "16384" }
    - { domain: "*", type: "hard", item: "maxlogins", value: "2" }

# Critical files to secure
security_critical_files:
  - { path: "/etc/passwd", mode: "0644" }
  - { path: "/etc/shadow", mode: "0600" }
  - { path: "/etc/group", mode: "0644" }
  - { path: "/etc/gshadow", mode: "0600" }
  - { path: "/etc/sudoers", mode: "0440" }

# Unused services to disable
security_unused_services:
  - avahi-daemon
  - cups
  - bluetooth
