---
galaxy_info:
  role_name: backup
  namespace: summitethic
  author: SummitEthic DevOps Team
  description: Simplified backup solution for basic server needs
  company: SummitEthic
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - focal    # 20.04
        - jammy    # 22.04
        - noble    # 24.04
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Debian
      versions:
        - bullseye  # 11
        - bookworm  # 12

  galaxy_tags:
    - backup
    - disaster-recovery
    - rsync
    - automation

dependencies: []

collections:
  - ansible.posix
  - community.general
