---
all:
  children:
    staging_servers:
      hosts:
        staging01:
          ansible_host: 10.0.2.10
          ansible_user: admin
      vars:
        docker_enabled: true
        traefik_enabled: true
        security_level: "basic"
        monitoring_bind_address: "0.0.0.0"
