---
# Optimized Firewall Role - Auto-Integrated
# Automatically discovers and configures services from other roles

firewall_enabled: true
firewall_default_policy: "deny"

# Auto-discovered service ports (integrated with other roles)
firewall_service_ports:
  ssh:
    port: "{{ common_ssh_port | default(22) }}"
    proto: "tcp"
    source: "{{ firewall_ssh_sources | default('0.0.0.0/0') }}"
    enabled: true
    comment: "SSH access"

  node_exporter:
    port: "{{ monitoring_node_exporter_port | default(9100) }}"
    proto: "tcp"
    source: "{{ firewall_monitoring_sources | default('127.0.0.1') }}"
    enabled: "{{ monitoring_node_exporter_enabled | default(false) }}"
    comment: "Node Exporter metrics"

  traefik_http:
    port: "{{ traefik_web_port | default(80) }}"
    proto: "tcp"
    source: "0.0.0.0/0"
    enabled: "{{ traefik_enabled | default(false) }}"
    comment: "Traefik HTTP"

  traefik_https:
    port: "{{ traefik_websecure_port | default(443) }}"
    proto: "tcp"
    source: "0.0.0.0/0"
    enabled: "{{ traefik_enabled | default(false) }}"
    comment: "Traefik HTTPS"

# Custom rules (user-defined)
firewall_custom_rules: []
#  - { port: 8080, proto: "tcp", source: "10.0.0.0/8", comment: "Custom app" }

# Source restrictions
firewall_ssh_sources: "0.0.0.0/0"
firewall_monitoring_sources: "127.0.0.1"

# Container integration
firewall_docker_integration: true
firewall_docker_bridge: "docker0"

# Rate limiting and security
firewall_enable_rate_limiting: true
firewall_rate_limit: "6/min"
firewall_enable_logging: true
firewall_log_level: "low"
