---
- name: Restart rsyslog
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted

- name: Restart journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted

- name: Restart Docker
  ansible.builtin.systemd_service:
    name: docker
    state: restarted
