---
- name: Restart rsyslog
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted

- name: Restart journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted

- name: Restart vector
  ansible.builtin.systemd_service:
    name: vector
    state: restarted

- name: Restart td-agent-bit
  ansible.builtin.systemd_service:
    name: td-agent-bit
    state: restarted

- name: Restart Docker
  ansible.builtin.systemd_service:
    name: docker
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
