---
- name: Restart SSH daemon
  ansible.builtin.systemd:
    name: "{{ common_ssh_service_name }}"
    state: restarted
  listen: restart sshd

- name: Restart fail2ban service
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  listen: restart fail2ban

- name: Restart rsyslog service
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
  listen: restart rsyslog

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd

- name: Restart node-exporter service
  ansible.builtin.systemd:
    name: node-exporter
    state: restarted
  listen: restart node-exporter

- name: Reboot system
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible for system updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  listen: reboot system

- name: Restart systemd-timesyncd service
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
  listen: restart systemd-timesyncd

- name: Restart systemd-journald service
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
  listen: restart systemd-journald
