---
# System packages for backup tools
backup_packages:
  - rsync
  - tar
  - gzip
  - bzip2
  - curl
  - postgresql-client  # for database backups
  - mysql-client       # for database backups

# Additional groups for backup user
backup_additional_groups:
  - "{{ 'docker' if backup_docker_enabled and ansible_facts['services']['docker.service'] is defined else omit }}"

# Restic version
backup_restic_version: "0.16.3"

# Backup configuration templates
backup_credential_templates:
  s3: |
    AWS_ACCESS_KEY_ID={{ backup_aws_access_key | default('') }}
    AWS_SECRET_ACCESS_KEY={{ backup_aws_secret_key | default('') }}
    RESTIC_PASSWORD={{ backup_password | default(ansible_machine_id) }}
  
  gcs: |
    GOOGLE_PROJECT_ID={{ backup_gcs_project | default('') }}
    GOOGLE_APPLICATION_CREDENTIALS={{ backup_gcs_credentials | default('') }}
    RESTIC_PASSWORD={{ backup_password | default(ansible_machine_id) }}
  
  azure: |
    AZURE_ACCOUNT_NAME={{ backup_azure_account | default('') }}
    AZURE_ACCOUNT_KEY={{ backup_azure_key | default('') }}
    RESTIC_PASSWORD={{ backup_password | default(ansible_machine_id) }}
