---
galaxy_info:
  role_name: firewall
  namespace: summitethic
  author: SummitEthic DevOps Team
  description: Modern network security configuration with OS-appropriate firewall management
  company: SummitEthic
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - focal    # 20.04
        - jammy    # 22.04
        - noble    # 24.04
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Debian
      versions:
        - bullseye  # 11
        - bookworm  # 12

  galaxy_tags:
    - firewall
    - security
    - network
    - ufw
    - firewalld
    - iptables

dependencies: []

collections:
  - community.general
  - ansible.posix
