---
- name: Install rsyslog
  ansible.builtin.package:
    name: rsyslog
    state: present
  tags: logging

- name: Configure rsyslog
  ansible.builtin.template:
    src: logging/rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: restart rsyslog
  tags: logging

- name: Create log directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /var/log/secure
    - /var/log/messages
    - /var/log/auth
  tags: logging

- name: Configure logrotate for system logs
  ansible.builtin.template:
    src: logging/logrotate.conf.j2
    dest: /etc/logrotate.d/system-logs
    owner: root
    group: root
    mode: '0644'
  when: common_enable_logrotate | bool
  tags: logging

- name: Set log file permissions
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: adm
    mode: '0640'
  loop:
    - /var/log/auth.log
    - /var/log/syslog
    - /var/log/kern.log
  failed_when: false
  tags: logging

- name: Enable and start rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    enabled: true
    state: started
  tags: logging

- name: Configure journal retention
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#?{{ item.key }}='
    line: '{{ item.key }}={{ item.value }}'
    state: present
  loop:
    - { key: 'SystemMaxUse', value: '1G' }
    - { key: 'SystemMaxFileSize', value: '100M' }
    - { key: 'MaxRetentionSec', value: '2week' }
    - { key: 'ForwardToSyslog', value: 'yes' }
  notify: restart systemd-journald
  tags: logging
