---
- name: Set system timezone
  ansible.builtin.command:
    cmd: timedatectl set-timezone {{ common_timezone }}
  when: common_timezone is defined
  changed_when: false
  tags: system

- name: Install NTP client
  ansible.builtin.package:
    name: systemd-timesyncd
    state: present
  when: common_enable_ntp | bool
  tags: system

- name: Configure NTP servers
  ansible.builtin.template:
    src: system/timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: '0644'
  when:
    - common_enable_ntp | bool
    - ansible_service_mgr == "systemd"
  notify: restart systemd-timesyncd
  tags: system

- name: Enable and start time synchronization
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: true
    state: started
  when:
    - common_enable_ntp | bool
    - ansible_service_mgr == "systemd"
  tags: system

- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when: common_set_hostname | default(true)
  tags: system

- name: Update /etc/hosts with hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 {{ inventory_hostname }}'
    state: present
  when: common_set_hostname | default(true)
  tags: system

- name: Configure swap usage
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ common_swappiness | default(10) }}"
    state: present
    reload: true
  tags: system

- name: Disable unnecessary kernel modules
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/blacklist-rare-network.conf
    line: "blacklist {{ item }}"
    create: true
    owner: root
    group: root
    mode: '0644'
  loop:
    - dccp
    - sctp
    - rds
    - tipc
  tags: [system, security]

- name: Set kernel parameters for performance
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/99-performance.conf
  loop:
    - { key: 'vm.dirty_ratio', value: '15' }
    - { key: 'vm.dirty_background_ratio', value: '5' }
    - { key: 'net.core.somaxconn', value: '65535' }
    - { key: 'net.core.netdev_max_backlog', value: '5000' }
    - { key: 'net.ipv4.tcp_max_syn_backlog', value: '8192' }
  tags: [system, performance]

- name: Create system maintenance script directory
  ansible.builtin.file:
    path: /opt/maintenance
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: system

- name: Install system info script
  ansible.builtin.copy:
    src: scripts/system-info.sh
    dest: /opt/maintenance/system-info.sh
    owner: root
    group: root
    mode: '0755'
  tags: system
