---
all:
  children:
    web_servers:
      hosts:
        web01:
          ansible_host: 10.0.1.10
          ansible_user: admin
        web02:
          ansible_host: 10.0.1.11
          ansible_user: admin
      vars:
        docker_enabled: true
        traefik_enabled: true
        security_level: "moderate"
        
    app_servers:
      hosts:
        app01:
          ansible_host: 10.0.1.20
          ansible_user: admin
        app02:
          ansible_host: 10.0.1.21
          ansible_user: admin
      vars:
        docker_enabled: true
        security_level: "moderate"
        
    db_servers:
      hosts:
        db01:
          ansible_host: 10.0.1.30
          ansible_user: admin
      vars:
        docker_enabled: false
        security_level: "strict"
        backup_enabled: true
        
    monitoring_servers:
      hosts:
        monitor01:
          ansible_host: 10.0.1.40
          ansible_user: admin
      vars:
        docker_enabled: true
        monitoring_bind_address: "0.0.0.0"
