---
# Modern Docker installation with security hardening
# Single file approach - no unnecessary complexity
# Uses FQCN and community.docker collection extensively

- name: Load OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  tags: [docker, always]

- name: Remove old Docker packages
  ansible.builtin.package:
    name: "{{ docker_old_packages }}"
    state: absent
  tags: [docker, install]

- name: Create keyring directory (Debian/Ubuntu)
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: 
    - ansible_os_family == "Debian"
    - docker_add_repo
  tags: [docker, install]

- name: Install Docker repository key (Debian/Ubuntu)
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  when: 
    - ansible_os_family == "Debian"
    - docker_add_repo
  tags: [docker, install]

- name: Add Docker repository (Debian/Ubuntu)
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] 
      https://download.docker.com/linux/{{ ansible_distribution | lower }} 
      {{ ansible_distribution_release }} stable
    filename: docker
    update_cache: true
  when: 
    - ansible_os_family == "Debian"
    - docker_add_repo
  tags: [docker, install]

- name: Add Docker repository (RedHat/CentOS)
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker CE Repository
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: true
  when: 
    - ansible_os_family == "RedHat"
    - docker_add_repo
  tags: [docker, install]

- name: Install Docker with all plugins
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true
  notify: restart docker
  tags: [docker, install]

- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present
  tags: [docker, users]

- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
  when: docker_users | length > 0
  tags: [docker, users]

- name: Create Docker configuration directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: '0755'
  tags: [docker, config]

- name: Configure Docker daemon
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
    backup: true
  notify: restart docker
  tags: [docker, config]

- name: Apply security hardening
  when: docker_security_enabled
  tags: [docker, security]
  block:
    - name: Create docker user namespace mapping user
      ansible.builtin.user:
        name: dockremap
        system: true
        shell: /bin/false
        create_home: false

    - name: Configure user namespace subordinate UID
      ansible.builtin.lineinfile:
        path: /etc/subuid
        line: "dockremap:165536:65536"
        create: true
        mode: '0644'
      notify: restart docker

    - name: Configure user namespace subordinate GID  
      ansible.builtin.lineinfile:
        path: /etc/subgid
        line: "dockremap:165536:65536"
        create: true
        mode: '0644'
      notify: restart docker

- name: Enable and start Docker service
  ansible.builtin.systemd_service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
    daemon_reload: true
  tags: [docker, service]

- name: Wait for Docker to be ready
  ansible.builtin.wait_for:
    path: /var/run/docker.sock
    timeout: 30
  tags: [docker, service]

- name: Set secure Docker socket permissions
  ansible.builtin.file:
    path: /var/run/docker.sock
    owner: root
    group: docker
    mode: '0660'
  tags: [docker, security]

- name: Verify Docker installation
  community.docker.docker_host_info:
  register: docker_info
  tags: [docker, verify]

- name: Verify Docker Compose plugin
  ansible.builtin.command:
    cmd: docker compose version
  register: compose_version
  changed_when: false
  tags: [docker, verify]

- name: Verify Docker Buildx plugin
  ansible.builtin.command:
    cmd: docker buildx version
  register: buildx_version
  changed_when: false
  tags: [docker, verify]

- name: Display Docker installation info
  ansible.builtin.debug:
    msg: 
      - "Docker version: {{ docker_info.host_info.ServerVersion }}"
      - "Docker Compose: {{ compose_version.stdout.split()[2] if compose_version.stdout else 'Available' }}"
      - "Docker Buildx: {{ buildx_version.stdout.split()[1] if buildx_version.stdout else 'Available' }}"
      - "Security hardening: {{ 'Enabled' if docker_security_enabled else 'Disabled' }}"
      - "Docker users: {{ docker_users | join(', ') if docker_users else 'None' }}"
  tags: [docker, verify]
