---
# Simplified Backup Role - Basic Needs Only
# Focus on essential backup functionality

# Basic backup configuration
backup_enabled: true
backup_tool: "rsync"
backup_user: "backup"

# Local backup (primary)
backup_local_enabled: true
backup_local_path: "/var/backups"

# Cloud backup (optional)
backup_cloud_enabled: false
backup_cloud_destination: ""

# What to backup - essential only
backup_system_paths:
  - "/etc"
  - "/home"
  - "/var/log"
  - "/root"

# Container backups
backup_docker_enabled: true
backup_docker_volumes: true
backup_docker_compose_dirs: []

# Database backups
backup_databases: []

# Retention policy
backup_retention_days: 7
backup_retention_weeks: 4

# Scheduling
backup_schedule_daily: "0 2 * * *"
backup_schedule_weekly: "0 3 * * 0"

# Options
backup_compression: true
backup_encryption: false
backup_monitoring: true
