---
# OS-specific variables with proper prefixes
common_ssh_package_name: "{{ common_ssh_package_name_map[ansible_os_family] }}"
common_ssh_service_name: "{{ common_ssh_service_name_map[ansible_os_family] }}"
common_node_exporter_version: "1.7.0"

common_ssh_package_name_map:
  Debian: openssh-server
  RedHat: openssh-server

common_ssh_service_name_map:
  Debian: ssh
  RedHat: sshd

# Package lists per OS family
common_packages_map:
  Debian:
    - curl
    - wget
    - git
    - vim
    - htop
    - tree
    - unzip
    - rsync
    - lsof
    - strace
    - tcpdump
    - net-tools
    - dnsutils
    - ca-certificates
    - gnupg
    - lsb-release
  RedHat:
    - curl
    - wget
    - git
    - vim
    - htop
    - tree
    - unzip
    - rsync
    - lsof
    - strace
    - tcpdump
    - net-tools
    - bind-utils
    - ca-certificates
    - gnupg2
    - redhat-lsb-core
