---
galaxy_info:
  role_name: docker
  namespace: summitethic
  author: SummitEthic DevOps Team
  description: Modern Docker installation with security hardening
  company: SummitEthic
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - focal    # 20.04
        - jammy    # 22.04
        - noble    # 24.04
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Debian
      versions:
        - bullseye  # 11
        - bookworm  # 12

  galaxy_tags:
    - docker
    - containerization
    - security
    - devops
    - container-platform

dependencies: []

collections:
  - community.docker
  - ansible.posix
